### ISSUE TITLE
Can not make

### ISSUE THREAD

**Issue by Heermod** [tsoding/multik#100]
Package sdl2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `sdl2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sdl2' found
Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable

ocamlc -c -ccopt "-Wall -Werror -Wconversion " src/cairo_matrix_impl.c -cclib ""
src/cairo_matrix_impl.c:7:10: fatal error: cairo.h: No such file or directory
 #include <cairo.h>
Both libs are installed.
Ubuntu 18.04

**Comment by rexim** [comment]
@Heermod have you installed `-dev` versions tho?

**Comment by Heermod** [comment]
Installed -dev and C++ wrappers libs now works.
